name: Train Model and save to wandb

on:
  push:
    branches:
      - main
    paths:
      - 'src/model/train.py'

jobs:
  train_model:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      #if: steps.setup.outputs.cache-hit != 'true'  
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Login to WandB
      run: wandb login ${{ secrets.WANDB_API_KEY }}
    - name: Run preprocess
      env:
        SEED: ${{ vars.SEED }}
        PROJECT_NAME: ${{ vars.PROJECT_NAME }}
        DATASET_NAME: ${{ vars.DATASET_NAME }}
        TRAIN_SIZE: ${{ vars.TRAIN_SIZE }}
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: python src/model/train.py --IdExecution ${{ github.run_number }}